# Generated by Django 3.2.25 on 2026-09-25 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefesto_http_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.URLField(default='https://localhost/hefesto/hefesto_web/data', validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
    ]
