# Generated by Django 3.0.2 on 2020-01-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ethernet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('dhcp', 'dhcp'), ('static', 'static')], default='dhcp', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_mask', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_dns', models.GenericIPAddressField(blank=True, null=True)),
                ('interface', models.CharField(blank=True, choices=[('eth0', 'eth0'), ('eth1', 'eth1')], default='eth0', max_length=100)),
            ],
            options={
                'verbose_name': 'ETHERNET',
            },
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('dhcp', 'dhcp'), ('static', 'static')], default='dhcp', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_mask', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_dns', models.GenericIPAddressField(blank=True, null=True)),
                ('interface', models.CharField(blank=True, choices=[('wlan0', 'wlan0'), ('wlan1', 'wlan1')], default='wlan0', max_length=100)),
                ('wifi_ssid', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'WIFI',
            },
        ),
    ]
