# Generated by Django 3.0.2 on 2020-01-26 15:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hefesto_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('habilitada', models.BooleanField(blank=True, default=True)),
                ('dispositivos', models.CharField(help_text='Lista dispositivos Ej: 1-3, 5, 7-9', max_length=50)),
                ('codigo_funcion', models.PositiveIntegerField(choices=[(3, 3), (4, 4), (6, 6), (16, 16)], default=3)),
                ('registro_inicio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(65535)])),
                ('numero_registros', models.PositiveIntegerField(default=1, help_text='Un registro son 2 BYTES Ej: un registro: 0xFFEE', validators=[django.core.validators.MaxValueValidator(127)])),
                ('tiempo_espera', models.FloatField(default=1, help_text='Numero de segundos para abortar la consulta sí no recibe respuesta.')),
                ('intervalo_muestreo', models.PositiveIntegerField(default=300, help_text='Tiempo en segundos.')),
                ('proximo_request', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('tipo_conexion', models.CharField(choices=[('RTU/SERIAL', 'RTU/SERIAL'), ('TCP/TCP', 'TCP/TCP')], default='RTU/SERIAL', max_length=100)),
                ('puerto_serial', models.CharField(blank=True, help_text='Si existe mas de un dispositivoUSB, las direcciones "/dev/ttyUSBx" no seran persistentes entre reinicios', max_length=50, null=True)),
                ('baudrate', models.PositiveIntegerField(blank=True, choices=[(9600, 9600), (19200, 19200), (38400, 38400), (56000, 56000), (57600, 57600), (76800, 76800), (115200, 115200)], default=9600, null=True)),
                ('numero_bytes', models.CharField(blank=True, choices=[('FIVEBITS', 'FIVEBITS'), ('SIXBITS', 'SIXBITS'), ('SEVENBITS', 'SEVENBITS'), ('EIGHTBITS', 'EIGHTBITS')], default='EIGHTBITS', max_length=50, null=True)),
                ('paridad', models.CharField(blank=True, choices=[('PARITY_NONE', 'PARITY_NONE'), ('PARITY_EVEN', 'PARITY_EVEN'), ('PARITY_ODD', 'PARITY_MARK'), ('PARITY_SPACE', 'PARITY_SPACE')], default='PARITY_NONE', max_length=50, null=True)),
                ('bit_parada', models.CharField(blank=True, choices=[('STOPBITS_ONE', 'STOPBITS_ONE'), ('STOPBITS_ONE_POINT_FIVE', 'STOPBITS_ONE_POINT_FIVE'), ('STOPBITS_TWO', 'STOPBITS_TWO')], default='STOPBITS_ONE', max_length=50, null=True)),
                ('puerto_tcp', models.PositiveIntegerField(blank=True, default=502, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, default='192.168.1.1', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariableLectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_dato', models.CharField(choices=[('>b', 'int8'), ('>h', 'int16'), ('>i', 'int32'), ('>q', 'int64'), ('>B', 'uint8'), ('>H', 'uint16'), ('>I', 'uint32'), ('>Q', 'uint64'), ('>f', 'float32'), ('>d', 'float64')], default='h', max_length=10)),
                ('byte_order', models.CharField(choices=[('AB', 'AB'), ('BA', 'BA'), ('ABCD', 'ABCD'), ('CDAB', 'CDAB'), ('BADC', 'BADC'), ('DCBA', 'DCBA'), ('ABCDEFGH', 'ABCDEFGH'), ('HGFEDCBA', 'HGFEDCBA')], default='AB', max_length=8)),
                ('desplazamiento', models.IntegerField(default=0, help_text='Numero de bytes para empezar a leer la respuesta.', validators=[django.core.validators.MaxValueValidator(254)])),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad N para leer N*Tipo_dato,  crea Nombre1..NombreN')),
                ('escala', models.FloatField(default=1, help_text='Factor para escalar la variable (1) primero escalaEj: (value*escala)+offset')),
                ('offset', models.FloatField(default=0, help_text='Cantidad a sumar a la variable')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hefesto_modbus.Consulta')),
            ],
            options={
                'unique_together': {('consulta', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ModbusTimeSerie',
            fields=[
                ('timeserie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hefesto_core.TimeSerie')),
                ('dev_id', models.PositiveIntegerField()),
                ('request_raw', models.CharField(max_length=500)),
                ('response_raw', models.CharField(max_length=500)),
                ('crc_ok', models.BooleanField()),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefesto_modbus.VariableLectura')),
            ],
            bases=('hefesto_core.timeserie',),
        ),
        migrations.CreateModel(
            name='VariableEscritura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('expresion', models.TextField()),
                ('tipo_dato', models.CharField(choices=[('>b', 'int8'), ('>h', 'int16'), ('>i', 'int32'), ('>q', 'int64'), ('>B', 'uint8'), ('>H', 'uint16'), ('>I', 'uint32'), ('>Q', 'uint64'), ('>f', 'float32'), ('>d', 'float64')], default='h', max_length=10)),
                ('byte_order', models.CharField(choices=[('AB', 'AB'), ('BA', 'BA'), ('ABCD', 'ABCD'), ('CDAB', 'CDAB'), ('BADC', 'BADC'), ('DCBA', 'DCBA'), ('ABCDEFGH', 'ABCDEFGH'), ('HGFEDCBA', 'HGFEDCBA')], default='AB', max_length=8)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hefesto_modbus.Consulta')),
            ],
            options={
                'unique_together': {('consulta', 'nombre')},
            },
        ),
    ]
