# Generated by Django 3.0.3 on 2020-04-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefesto_modbus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablelectura',
            name='longitud_texto',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='variableescritura',
            name='tipo_dato',
            field=models.CharField(choices=[('>b', 'int8'), ('>h', 'int16'), ('>i', 'int32'), ('>q', 'int64'), ('>B', 'uint8'), ('>H', 'uint16'), ('>I', 'uint32'), ('>Q', 'uint64'), ('>f', 'float32'), ('>d', 'float64'), ('s', 'ascii')], default='h', max_length=10),
        ),
        migrations.AlterField(
            model_name='variablelectura',
            name='tipo_dato',
            field=models.CharField(choices=[('>b', 'int8'), ('>h', 'int16'), ('>i', 'int32'), ('>q', 'int64'), ('>B', 'uint8'), ('>H', 'uint16'), ('>I', 'uint32'), ('>Q', 'uint64'), ('>f', 'float32'), ('>d', 'float64'), ('s', 'ascii')], default='h', max_length=10),
        ),
    ]
