# Generated by Django 3.0.2 on 2020-01-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefesto_core', '0002_task_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
