# Generated by Django 3.0.3 on 2020-03-01 01:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hefesto_core', '0003_auto_20200126_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeserie',
            name='value',
        ),
        migrations.AddField(
            model_name='timeserie',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
