# Generated by Django 6.1.1 on 2026-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hefesto_core', '0004_auto_20200229_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeserie',
            name='context',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='timeserie',
            name='exported',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='timeserie',
            name='value',
            field=models.JSONField(default=dict),
        ),
    ]
