# Generated by Django 3.0.2 on 2020-01-28 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_string', models.TextField()),
                ('habilitado', models.BooleanField(default=True, help_text='Habilitar el agente de envio.')),
                ('tiempo_entre_envios', models.IntegerField(default=900, help_text='Tiempo en segundos.')),
                ('tiempo_entre_peticiones', models.IntegerField(default=1800, help_text='Tiempo en segundos.', validators=[django.core.validators.MinValueValidator(1500)])),
                ('gzip_habilitado', models.BooleanField(default=False, help_text='Habilitar compresion.')),
            ],
            options={
                'verbose_name': 'AZURE IoTHub',
            },
        ),
    ]
